project:
  type: website
  output-dir: docs
website:
   google-analytics: "G-4HE60YY1JD"
   favicon: images/r_favicon.png
   navbar:
    title: false
    logo: images/logo.png
    site-url: https://www.rleripio.com
    left:
      - href: index.qmd
        text: Home
      - book.qmd
      - talks.qmd
reader-mode: true
format:
  html:
    page-layout: full
    theme: litera
    css: styles.css
    toc: true